DROP TABLE IF EXISTS product;

DROP TYPE IF EXISTS product_type;

DROP TABLE IF EXISTS reception;

DROP TYPE IF EXISTS status;

DROP TABLE IF EXISTS pvz;

DROP TYPE IF EXISTS city;

DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS role;