services:
  postgres:
    image: postgres:17-alpine
    command: 
      -c max_connections=600
      -c shared_buffers=120MB
      -c tcp_keepalives_idle=30
      -c tcp_keepalives_interval=10
      -c tcp_keepalives_count=5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"
    networks:
      - backend-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  migrate:
      image: migrate/migrate
      networks:
          - backend-net
      volumes:
          - ./migrations/:/migrations
      command: ["-path", "/migrations", "-database", "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD:-invalid}@postgres:5432/${POSTGRES_DB}?sslmode=disable", "up"]
      links:
        - postgres
      depends_on:
        postgres:
          condition: service_healthy

  
networks:
  backend-net:
    driver: bridge
