services:
  app:
    build: 
      context: .
      dockerfile: build/package/Dockerfile
    container_name: app
    env_file: .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - GIT_MODE=release
    ports:
      - "8080:8080" # http server
      - "3000:3000" # grpc server
      - "9000:9000" # metrics server
    depends_on:
      - postgres
      - migrate
    networks:
      - backend-net

  postgres:
    image: postgres:17-alpine
    command: 
      -c max_connections=600
      -c shared_buffers=120MB
      -c tcp_keepalives_idle=30
      -c tcp_keepalives_interval=10
      -c tcp_keepalives_count=5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - backend-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  migrate:
      image: migrate/migrate
      networks:
          - backend-net
      volumes:
          - ./db/migrations/:/migrations
      command: ["-path", "/migrations", "-database", "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD:-invalid}@postgres:5432/${POSTGRES_DB}?sslmode=disable", "up"]
      links:
        - postgres
      depends_on:
        postgres:
          condition: service_healthy

  prometheus:
    image: prom/prometheus
    volumes:
      - "./configs/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - backend-net
    ports:
      - 9090:9090
  
networks:
  backend-net:
    driver: bridge
