// Code generated by MockGen. DO NOT EDIT.
// Source: ./user_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	db "github.com/myacey/avito-backend-assignment-pvz/internal/repository/sqlc"
)

// MockUserQueries is a mock of UserQueries interface.
type MockUserQueries struct {
	ctrl     *gomock.Controller
	recorder *MockUserQueriesMockRecorder
}

// MockUserQueriesMockRecorder is the mock recorder for MockUserQueries.
type MockUserQueriesMockRecorder struct {
	mock *MockUserQueries
}

// NewMockUserQueries creates a new mock instance.
func NewMockUserQueries(ctrl *gomock.Controller) *MockUserQueries {
	mock := &MockUserQueries{ctrl: ctrl}
	mock.recorder = &MockUserQueriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserQueries) EXPECT() *MockUserQueriesMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserQueries) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserQueriesMockRecorder) CreateUser(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserQueries)(nil).CreateUser), ctx, arg)
}

// GetUserByEmail mocks base method.
func (m *MockUserQueries) GetUserByEmail(ctx context.Context, email string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserQueriesMockRecorder) GetUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserQueries)(nil).GetUserByEmail), ctx, email)
}
