// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddProductToReception(ctx context.Context, arg AddProductToReceptionParams) (Product, error)
	CreatePVZ(ctx context.Context, arg CreatePVZParams) (Pvz, error)
	CreateReception(ctx context.Context, arg CreateReceptionParams) (Reception, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	FinishReception(ctx context.Context, pvzID uuid.UUID) (Reception, error)
	GetLastProductInReception(ctx context.Context, receptionID uuid.UUID) (Product, error)
	GetOpenReceptionByPvzID(ctx context.Context, pvzID uuid.UUID) (Reception, error)
	GetProductsFromReception(ctx context.Context, receptionID uuid.UUID) ([]Product, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	SearchPVZ(ctx context.Context, arg SearchPVZParams) ([]Pvz, error)
	SearchReceptionsByPvzsAndTime(ctx context.Context, arg SearchReceptionsByPvzsAndTimeParams) ([]Reception, error)
	SearchReceptionsByTime(ctx context.Context, arg SearchReceptionsByTimeParams) ([]Reception, error)
}

var _ Querier = (*Queries)(nil)
