// Code generated by MockGen. DO NOT EDIT.
// Source: ./pvz_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	request "github.com/myacey/avito-backend-assignment-pvz/internal/models/dto/request"
	entity "github.com/myacey/avito-backend-assignment-pvz/internal/models/entity"
)

// MockPvzRepo is a mock of PvzRepo interface.
type MockPvzRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPvzRepoMockRecorder
}

// MockPvzRepoMockRecorder is the mock recorder for MockPvzRepo.
type MockPvzRepoMockRecorder struct {
	mock *MockPvzRepo
}

// NewMockPvzRepo creates a new mock instance.
func NewMockPvzRepo(ctrl *gomock.Controller) *MockPvzRepo {
	mock := &MockPvzRepo{ctrl: ctrl}
	mock.recorder = &MockPvzRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPvzRepo) EXPECT() *MockPvzRepoMockRecorder {
	return m.recorder
}

// CreatePvz mocks base method.
func (m *MockPvzRepo) CreatePvz(ctx context.Context, req *request.CreatePvz) (*entity.Pvz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePvz", ctx, req)
	ret0, _ := ret[0].(*entity.Pvz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePvz indicates an expected call of CreatePvz.
func (mr *MockPvzRepoMockRecorder) CreatePvz(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePvz", reflect.TypeOf((*MockPvzRepo)(nil).CreatePvz), ctx, req)
}

// SearchPvz mocks base method.
func (m *MockPvzRepo) SearchPvz(ctx context.Context, req *request.SearchPvz) ([]*entity.Pvz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPvz", ctx, req)
	ret0, _ := ret[0].([]*entity.Pvz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPvz indicates an expected call of SearchPvz.
func (mr *MockPvzRepoMockRecorder) SearchPvz(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPvz", reflect.TypeOf((*MockPvzRepo)(nil).SearchPvz), ctx, req)
}
